import { Dimensions, StyleSheet } from "react-native";
const { height, width } = Dimensions.get('window')


export const styles = StyleSheet.create({

	SrchBtnImg: {
		resizeMode: 'contain',
		width: width * 0.1,
		height: height * 0.045,
	},
	AuthView: {
		display: 'flex',
		width: width,
		height: height,
	},
	SingleDisplay:{
		display: 'flex',
		alignSelf: 'center',
		width : width * 0.9,
		height : height * 0.9,
		alignItems: 'center',
		zIndex: 10,
	},
	ImgCntnAccnt: {
		width : width * 0.125,
		height : height* 0.125,
		resizeMode: 'contain',
	},
	CntnAccnt: {
		display: 'flex',
		width : width * 0.125,
		height : height* 0.125,
	},
	AccountFzone: {
		adisplay: 'flex',
		flexDirection: 'row',
},
	ImageSizer:{
		width: width,
		height: height,
	},
	pagebtn: {
		fontSize: 25,
	},
	backbtn: {
		fontSize: 21,
		color: 'white',
	},
	ButtonMenu: {
		alignItems: 'center',
		justifyContent: 'center',
		width: '100%',
		height: '100%',
		borderRadius: 4,
		elevation: 3,
		backgroundColor: 'white',
	},
	MenuBtnText: {
		textAlign: 'center',
		fontSize: 20,
	},
	MenuBtn: {
		alignItems: 'center',
		justifyContent: 'center',
		alignContent: 'center',
		borderRightColor: 'black',
		borderRightWidth: 1,
		height: '100%',
		width: width * 0.225,
	},
	MenuCntr:{
		position: 'absolute',

		zIndex: 100,
	},
	MenuBtnSpeR: {
		justifyContent: 'center',
		alignItems: 'center',
		borderRightWidth: 0,
		height: '100%',
		width: width * 0.225,
	},
	Webview: {
		height: '100',
	},
	MenuCard: {
		display: 'flex',
		flexDirection: 'row',
		borderRadius: 7,
		width: width * 0.9,
		height: height * 0.1,
		bottom: width / 4.5,
		marginTop: height * 0.3,
		backgroundColor: 'white',
	},
	Body: {
		flexDirection: 'column',
		alignContent: 'center',
		justifyContent: 'center',
		flex: 1,
	},
	IcoR: {
		width: width / 25,
		height: height / 20,
	},
	MicoR: {
		width: width / 27,
		height: height / 20,
	},
	Ico: {
		width: width / 11,
		height: height / 25,
	},
	Mico: {
		width: width / 12,
		height: height / 25,
	},
	Header: {
		width: width * 9 / 10,
		display: 'flex',
		justifyContent: 'space-between',
		flexDirection: 'row',
	},
	SearchMenu: {
		flex: 1,
		justifyContent: 'center',
		display: 'flex',
		flexDirection: 'row',
	},
	SearchBtn: {
		flex: 3,
	},
	SearchBar: {
		color: '#fff',
		backgroundColor: '#ffff',
		height: height * 1 / 22,
		width: width * 0.4,
		borderRadius: 25,
		marginBottom: 10,
	},
	Text: {
		color: '#fff',
		fontSize: 30,
	},
	container: {
		paddingTop: height / 20,
		flex: 1,
		backgroundColor: '#004B88',
		alignItems: 'center',
		display: 'flex',
		justifyContent: 'space-between',
	},


	cont: {
		overflow: "hidden",
		marginTop: width * 0.05,
		width: width * 1,
		height: height * 1,
		display: "flex",
		backgroundColor: 'pink',
	},
	card: {
		backgroundColor: '#fff',
		alignItems: 'center',
		width: width * 0.9,
		height: height * 0.7,
		borderRadius: 25,
	},
	NavImg: {
		maxHeight: 80,
		maxWidth: 80,
		resizeMode: 'contain',
	},
	NavBarView: {
		display: 'flex',
		flexDirection: "row",
		backgroundColor: '#c45305',
		flex: 1,
	},
	BackBtn: {
		marginLeft: 7,
		resizeMode: "contain",
		height: 60,
		width: 69,
	},
	Modal: {
		marginTop: 60,
		paddingBottom: width * 0.15,
		display: 'flex',
		alignItems: 'center',
		width: width / 3,
		justifyContent: 'center',
		zIndex: 100,
		top: 0,
		left:0,
		height :  height,
		borderRightWidth: 3,
		backgroundColor: 'white',
		borderTopWidth: 3,
		borderColor: 'orange',
		borderRadius: 10,
	},
	Flitr: {
		display: 'flex',
		height: 30,
		width: 90,
		margin: 2,
		justifyContent: "center",
		alignItems: "center",
		backgroundColor: 'yellow',
		borderRadius: 30,
		borderColor: 'black',
		borderWidth: 1,
	},
	ScreenContainer: {
		borderRadius: 50,
		alignSelf: 'center',
		justifyContent: 'center',
		flex: 1,
		padding: 17,
		width: width * 0.95,
		height: height * 0.772,
	},
	FilterSlctr: {
		width: 70,
		height: 70,
		resizeMode: 'contain',
	},
	FilterZone: {
		alignItems: "center",
		margin: -20,
		display: 'flex',
		flexDirection: 'row',
		flexWrap: 'wrap',
	},
	SlctrView: {

		flex: 0.5,
	},
	SearchSlctr: {
		width: 60,
		height: 60,
		resizeMode: 'contain',
	},
	clearBtn:{
		position: "absolute",
		zIndex: 160,
		top : 20,
		right: 20,
		padding: 9,
		margin: 10,
		backgroundColor: 'orange',
	},
	searchZn: {
		backgroundColor: 'white',
		flex: 2,
		marginTop: 10,
		fontSize: 17,
		alignContent: "center",
		textAlign: "center",
		fontWeight: "bold",
		height: height * 0.06,
		borderRadius: 50,

	},
	Any:
	{
		flex: 1,
		display: 'flex',
		flexDirection: 'row'
	},

	FilterModal: {
		flex: 1,
	},
	ImgContain: {
		zIndex: 1,
		display: 'flex',
		height: height * 0.1,
		width: width * 0.3,
		resizeMode: 'contain',
	},
	ModalSearch: {
		alignSelf: 'center',
		height: height * 0.1,
		display: 'flex',
		flexDirection: "row",
		alignItems: 'center',
		paddingLeft: 15,
		borderRadius: 20,
		width: width / 3,
		backgroundColor: 'orange',
	},
	AccountCont: {
		width: width * 0.3334,
		height: height* 0.6,
		backgroundColor: 'white',
		zIndex: 10,
		position: 'absolute',
		right: 0,
		bottom: 0,
		display: 'flex',
		alignItems: 'flex-end',
		justifyContent: 'flex-end',
	},
	MenuSlctr: {
		height: height * 0.1,
		width: width * 0.3,
		alignItems: 'center',
		margin: 10,
		marginTop: 30,
		borderRadius: 40,
		justifyContent: 'center',
		backgroundColor: 'orange',
	},
	WHText: {
		fontSize: 17,
		fontWeight: 'bold',
		zIndex: 2,
		color: 'white',
	},
	BlkText: {
		fontSize: 17,
		fontWeight: 'bold',
		zIndex: 2,
		color: 'black',
	},
	MjrT1: {
		fontSize: 17,
		fontWeight: 'bold',
	},
	MenuSlctrblk: {
		height: height * 0.1,
		width: width * 0.3,
		alignItems: 'center',
		margin: 10,
		marginTop: 30,
		borderRadius: 40,
		justifyContent: 'center',
		backgroundColor: 'black',
	},
	ModalLeft: {
		height: height * 0.6,
		paddingTop: 30,
		alignItems: 'center',
		width: width / 2.98,
		right:0,
		borderLeftWidth: 3,
		borderTopWidth: 3,
		borderRadius: 10,
		borderColor: 'orange',
	},
	MainView: {
		flex: 7,
		backgroundColor: 'white',
	},
	ScrollView: {
		display: 'flex',
	},
	NavImgSrch: {
		maxHeight: 65,
		maxWidth: 65,
	},
	NavPart: {

		display: 'flex',
		alignItems: 'center',
		flex: 1,
		justifyContent: 'center',
		backgroundColor: 'orange',
		borderRightColor: 'purple',
		borderRightWidth: 2,
	},
	NavImgMenu: {
		maxHeight: 55,
		maxWidth: 60,
		resizeMode: 'contain',
	},
});